### PR TITLE
ci: update actions/checkout to v3

### LINKED ISSUE #459: Node.js 12 actions are deprecated in GitHub Actions
### The issue

CI logs say:

```console
check_labels
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```

### The context

_No response_

### Possible solution

update `actions/checkout`.

### Confirmation

- [X] This report is not a bug report in code, a question, nor a request for drivers.

### PR DESCRIPTION
**Pull request by trombik**
fixes #459

### CODE REVIEW

File: components/bme680/bme680.c [hunk 1]
```diff
@@ -724,9 +724,8 @@ esp_err_t bme680_get_measurement_duration(const bme680_t *dev, uint32_t *duratio
     // some ms tolerance
     *duration += 5;
 
-    // ceil to next integer value that is divisible by portTICK_PERIOD_MS and
-    // compute RTOS ticks (1 ... portTICK_PERIOD_MS =  1 tick)
-    *duration = (*duration + portTICK_PERIOD_MS - 1) / portTICK_PERIOD_MS;
```
Comment (trombik) [inline components/bme680/bme680.c:729]: @UncleRus if i understand it correctly, the above comment can be ignored. am I right?

Comment (trombik) [reply components/bme680/bme680.c:729]: sorry, i'll create another PR for that as i found another deprecation warning.

**Comment by trombik** [comment]
finally, no warning.
